"""empty message

Revision ID: 23020e70b2e5
Revises: 9690e0124c79
Create Date: 2020-06-06 13:50:44.642129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23020e70b2e5'
down_revision = '9690e0124c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
